# These files are rewritten by the PlatformIO VS Code extension when the project
# is opened, so exclude them from the formatting and sorting hooks.
exclude: |
  (?x)^(
      \.vscode/c_cpp_properties\.json|
      \.vscode/extensions\.json|
      \.vscode/launch\.json
  )$
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # frozen: v6.0.0
    hooks:
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: trailing-whitespace
      - id: check-merge-conflict
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: dd18dad857d6133e90bbe478f4f2f22ec0030269 # frozen: v22.1.5
    hooks:
      - id: clang-format
        files: \.(c|cc|cpp|cxx|h|hh|hpp|hxx)$
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: "c7c1c7640e610068e8e4754e9f1bf109bd987dc7" # post-v0.48.0 with patches
    hooks:
      - id: markdownlint
        args:
          - --fix
  - repo: https://github.com/tillig/json-sort-cli
    rev: 2b7e147e0933bd30b58133b6f287e5c695ff4f0e # frozen: v3.0.1
    hooks:
      - id: json-sort
        args:
          - --autofix
